spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:7899/trip_corp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: trip1234

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret: ILoveTripCorpILikeTripCorpIWantToTripCorpTripCorpHooray