spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/trip_corp
    username: sa
    password: 1234

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: ILoveTripCorpILikeTripCorpIWantToTripCorpTripCorpHooray